---
- name: add repo nginx
  template: src=../../../templates/nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo
  tags: nginx

- name: install nginx
  yum: name=nginx state=present
  tags: nginx

- name: add fastcgi setting for php-fpm
  lineinfile:
    dest=/etc/nginx/fastcgi_params
    regexp=''
    insertafter=EOF
    line='fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;'
  tags: nginx

- name: stat sites-enabled nginx directory
  stat: path=/etc/nginx/sites-enabled
  register: stat_nginx_dir
  tags: nginx

- name: create sites-enabled directory
  file: path=/etc/nginx/sites-enabled state=directory mode=775
  when: not stat_nginx_dir.stat.exists
  tags: nginx

- name: add nginx configuration
  template: src=../../../templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  tags: nginx

- name: add berkas project configuration
  template: src=../../../templates/{{ project_name }}.conf.j2 dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
  tags: nginx

- name: restart nginx service
  command: systemctl restart nginx
  tags: nginx

- name: enable nginx service
  command: systemctl enable nginx
  tags: nginx
